version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  unit_test:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1- # Gunakan key cache yang sesuai dengan kebutuhan unit test
      - run:
          name: Give gradlew permission
          command: chmod +x ./gradlew
      - run:
          name: Run Unit Test
          command: ./gradlew clean test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: unit-test-report

workflows:
  unit_test_workflow:
    jobs:
      - unit_test