version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      tag: default
    steps:
      - checkout

      - run:
          name: Give gradlew permission
          command: chmod +x ./gradlew

      - run:
          name: Clean project
          command: ./gradlew clean

      - run:
          name: Run Unit Tests
          command: ./gradlew test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: unit-test-report

workflows:
  test-workflow:
    jobs:
      - unit-test
